name: Deploy to cPanel (Port 2222)

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      # ======================
      # SSH SETUP (PORT 2222)
      # ======================
      - name: Configure SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          
          # Get host key for port 2222
          ssh-keyscan -p 2222 ${{ secrets.DEPLOY_HOST }} > $HOME/.ssh/known_hosts
          echo "Host key for port 2222:"
          cat $HOME/.ssh/known_hosts

      # ======================
      # DEPLOYMENT
      # ======================
      - name: Deploy via SSH with Git LFS Support
        run: |
          ssh -p 2222 -i $HOME/.ssh/id_ed25519 \
          -o StrictHostKeyChecking=yes \
          -o ConnectTimeout=15 \
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            rm -rf ~/public_html
            git clone --depth=1 git@github.com:AlejCast02/PetyrRolls.git ~/public_html
            cd ~/public_html
            git lfs install
            git lfs pull
