name: Deploy to cPanel (Port 2222)
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3

      # ======================
      # SSH SETUP
      # ======================
      - name: Configure SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          echo "[${{ secrets.DEPLOY_HOST }}]:2222 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI..." > $HOME/.ssh/known_hosts

      # ======================
      # CONNECTION TEST
      # ======================
      - name: Test Port 2222
        run: |
          echo "Testing port 2222..."
          nc -zv ${{ secrets.DEPLOY_HOST }} 2222 && echo "Port test passed!" || echo "Port test failed"

      # ======================
      # DEPLOYMENT
      # ======================
      - name: Deploy via SSH (Port 2222)
        run: |
          ssh -p 2222 -i $HOME/.ssh/id_ed25519 \
          -o StrictHostKeyChecking=yes \
          -o ConnectTimeout=15 \
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "cd ~/repositories/PetyrRolls.git && \
          git fetch origin && \
          git reset --hard origin/master && \
          echo 'Deployed commit: $(git log -1 --pretty=%B)'"
