name: SSH Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p $HOME/test_dir
          echo "Test file" > $HOME/test_dir/test.txt
          ls -la $HOME/
          
      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 \
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "cd ~/repositories/PetyrRolls.git && git pull && echo 'Deploy complete'"
